# ganesha.conf

NFS_CORE_PARAM {
    MNT_Port = 20048;
    NFS_Port = 2049;

    # Enforce NFSv4 only
    Protocols = 4; 

    # Completely shut down UDP listener socket creation
    Enable_UDP = false;

    # Kill the RQUOTA subsystem (Stops the "RQUOTA V1 on UDP" warning)
    Enable_RQUOTA = false;

    # Kill the NFSv3 Lock Manager (Not needed for NFSv4)
    Enable_NLM = false;
}

LOG {
    Default_Log_Level = INFO;

    Facility {
        Name = FILE;
        Destination = "/tmp/ganesha.log";
    }

    # Component {
    #     FSAL = DEBUG;
    #     NFS4 = DEBUG;
    #     NFS_V3 = DEBUG;
    #     CACHE_INODE = DEBUG;
    # }
}

EXPORT {
    Export_Id = 1;
    Path = "/";     # The real local path we mounted above
    Pseudo = "/";   # The virtual path clients use to mount

    FSAL {
        Name = DOTFS;
    }
}

NFSv4 {
    RecoveryBackend = "fs";
}

DOTFS {
    socket_path = "/var/run/dotfs/ganesha.sock";
    fs_socket_path = "/var/run/dotfs/dotfs.sock";
}
