/*
 * DO NOT EDIT THIS FILE.
 * Code generated by wireforge.
 *
 * This file implements the serialization, deserialization, stream I/O, and
 * memory management functions declared in messages.h.
 */

#include <stdlib.h>
#include <string.h>

#include "messages.h"

/* ---------------------------------------------------------------------------
 * Big-Endian encoding/decoding helpers
 * These ensure consistent wire format regardless of host CPU byte order.
 * ---------------------------------------------------------------------------*/

static inline void put_u16_be(uint8_t* buf, uint16_t val) {
    buf[0] = (uint8_t)(val >> 8);
    buf[1] = (uint8_t)(val);
}

static inline void put_u32_be(uint8_t* buf, uint32_t val) {
    buf[0] = (uint8_t)(val >> 24);
    buf[1] = (uint8_t)(val >> 16);
    buf[2] = (uint8_t)(val >> 8);
    buf[3] = (uint8_t)(val);
}

static inline void put_u64_be(uint8_t* buf, uint64_t val) {
    buf[0] = (uint8_t)(val >> 56);
    buf[1] = (uint8_t)(val >> 48);
    buf[2] = (uint8_t)(val >> 40);
    buf[3] = (uint8_t)(val >> 32);
    buf[4] = (uint8_t)(val >> 24);
    buf[5] = (uint8_t)(val >> 16);
    buf[6] = (uint8_t)(val >> 8);
    buf[7] = (uint8_t)(val);
}

static inline uint16_t get_u16_be(const uint8_t* buf) {
    return (uint16_t)((uint16_t)buf[0] << 8 | (uint16_t)buf[1]);
}

static inline uint32_t get_u32_be(const uint8_t* buf) {
    return (uint32_t)buf[0] << 24 | (uint32_t)buf[1] << 16 |
           (uint32_t)buf[2] << 8  | (uint32_t)buf[3];
}

static inline uint64_t get_u64_be(const uint8_t* buf) {
    return (uint64_t)buf[0] << 56 | (uint64_t)buf[1] << 48 |
           (uint64_t)buf[2] << 40 | (uint64_t)buf[3] << 32 |
           (uint64_t)buf[4] << 24 | (uint64_t)buf[5] << 16 |
           (uint64_t)buf[6] << 8  | (uint64_t)buf[7];
}

uint16_t get_message_type(const uint8_t* buf) {
    return get_u16_be(buf);
}

uint16_t get_message_fixed_length(const uint8_t* buf) {
    return get_u16_be(buf + WIRE_FRAME_MSG_TYPE_SIZE);
}


/* ===========================================================================
 * ReadRequest (Type ID: 1, Fixed Header: 12 bytes)
 * ===========================================================================*/

/**
 * Sets the value of the count field in the read_request_t struct.
 */
void read_request_set_count(read_request_t* msg, const int32_t value) {
    if (msg) msg->count = value;
}

/**
 * Sets the value of the offset field in the read_request_t struct.
 */
void read_request_set_offset(read_request_t* msg, const int32_t value) {
    if (msg) msg->offset = value;
}

/**
 * Sets the value of the key field in the read_request_t struct.
 */
void read_request_set_key(read_request_t* msg, const char* value) {
    if (!msg || !value) return;
    if (msg->key != NULL) {
        free(msg->key);
    }

    size_t len = strlen(value);
    char* new_value = (char*) malloc(len + 1);
    if (!new_value) return;

    memcpy(new_value, value, len + 1);
    msg->key = new_value;
    msg->key_len = (uint32_t)len;
}

/**
 * calculate_read_request_dynamic_payload_size - Compute the total size of
 * all variable-length fields in the ReadRequest message from the fixed header.
 */
size_t calculate_read_request_dynamic_payload_size(const uint8_t* hdr_buf) {
    if (!hdr_buf) return 0;
    size_t dyn_total = 0;
    uint32_t key_len = get_u32_be(hdr_buf + 8);
    dyn_total += key_len;
    return dyn_total;
}

/**
 * read_request_marshal - Serialize ReadRequest to wire format.
 *
 * Writes the complete framed message into out_buf:
 *   [0:2]     Type ID (1, Big-Endian)
 *   [2:4]     Fixed header length (12, Big-Endian)
 *   [4:16]    Fixed header (fields + padding, Big-Endian encoded)
 *   [16:end]  Dynamic payload (variable-length field data)
 */
int read_request_marshal(const read_request_t* msg, uint8_t** out_buf) {
    if (!msg || !out_buf) return -1;

    /* Calculate total dynamic payload size from all variable-length fields */
    size_t dyn_size = 0;
    dyn_size += msg->key_len;

    size_t total = WIRE_FRAME_HEADER_SIZE + READ_REQUEST_FIXED_SIZE + dyn_size;
    if (total > MAX_ALLOWED_PACKET) return -1;

    uint8_t* buf = (uint8_t*)malloc(total);
    if (!buf) return -1;

    memset(buf, 0, WIRE_FRAME_HEADER_SIZE + READ_REQUEST_FIXED_SIZE);

    /* Write wire frame header identifiers */
    put_u16_be(buf, READ_REQUEST_TYPE_ID);
    put_u16_be(buf + WIRE_FRAME_MSG_TYPE_SIZE, READ_REQUEST_FIXED_SIZE);

    uint8_t* hdr = buf + WIRE_FRAME_HEADER_SIZE;
    size_t dyn_off = WIRE_FRAME_HEADER_SIZE + READ_REQUEST_FIXED_SIZE;
    put_u32_be(hdr + 0, (uint32_t)msg->count);
    put_u32_be(hdr + 4, (uint32_t)msg->offset);
    put_u32_be(hdr + 8, msg->key_len);
    if (msg->key_len > 0 && msg->key) {
        memcpy(buf + dyn_off, msg->key, msg->key_len);
        dyn_off += msg->key_len;
    }

    (void)dyn_off;
    *out_buf = buf;
    return (int)total;
}

/**
 * read_request_unmarshal - Deserialize ReadRequest from a contiguous buffer.
 *
 * in_buf points to the start of the fixed header (after the 4-byte frame header).
 * Variable-length fields are malloc'd; caller must call read_request_free().
 * On any error, partial allocations are cleaned up before returning.
 */
int read_request_unmarshal(const uint8_t* in_buf, size_t in_len, uint16_t fixed_header_len, read_request_t* out_msg) {
    if (!in_buf || !out_msg ||
        fixed_header_len < READ_REQUEST_FIXED_SIZE ||
        in_len < fixed_header_len ||
        in_len > MAX_ALLOWED_PACKET) {
        return -1;
    }

    memset(out_msg, 0, sizeof(read_request_t));

    const uint8_t* hdr = in_buf;
    size_t dyn_off = fixed_header_len;

    /* Decode fixed-size primitives from structural block offsets */
    out_msg->count = (int32_t)get_u32_be(hdr + 0);
    out_msg->offset = (int32_t)get_u32_be(hdr + 4);
    out_msg->key_len = get_u32_be(hdr + 8);

    /* Decode variable-length dynamic fields safely */
    if (out_msg->key_len > 0) {
        if (out_msg->key_len > MAX_ALLOWED_PACKET || dyn_off + out_msg->key_len > in_len) {
            read_request_free(out_msg);
            return -1;
        }
        out_msg->key = (char*) malloc(out_msg->key_len + 1);
        if (!out_msg->key) {
            read_request_free(out_msg);
            return -1;
        }

        memcpy(out_msg->key, in_buf + dyn_off, out_msg->key_len);
        out_msg->key[out_msg->key_len] = '\0';
        dyn_off += out_msg->key_len;
    }

    (void)dyn_off;
    return 0;
}

/**
 * read_request_free - Release heap memory owned by a read_request_t struct.
 */
void read_request_free(read_request_t* msg) {
    if (!msg) return;
    if (msg->key) {
        free(msg->key);
        msg->key = NULL;
    }
    msg->key_len = 0;
}


/* ===========================================================================
 * ReadResponse (Type ID: 2, Fixed Header: 8 bytes)
 * ===========================================================================*/

/**
 * Sets the value of the bytes_read field in the read_response_t struct.
 */
void read_response_set_bytes_read(read_response_t* msg, const int32_t value) {
    if (msg) msg->bytes_read = value;
}

/**
 * Sets the value of the data field in the read_response_t struct.
 */
void read_response_set_data(read_response_t* msg, const char* value) {
    if (!msg || !value) return;
    if (msg->data != NULL) {
        free(msg->data);
    }

    size_t len = strlen(value);
    char* new_value = (char*) malloc(len + 1);
    if (!new_value) return;

    memcpy(new_value, value, len + 1);
    msg->data = new_value;
    msg->data_len = (uint32_t)len;
}

/**
 * calculate_read_response_dynamic_payload_size - Compute the total size of
 * all variable-length fields in the ReadResponse message from the fixed header.
 */
size_t calculate_read_response_dynamic_payload_size(const uint8_t* hdr_buf) {
    if (!hdr_buf) return 0;
    size_t dyn_total = 0;
    uint32_t data_len = get_u32_be(hdr_buf + 4);
    dyn_total += data_len;
    return dyn_total;
}

/**
 * read_response_marshal - Serialize ReadResponse to wire format.
 *
 * Writes the complete framed message into out_buf:
 *   [0:2]     Type ID (2, Big-Endian)
 *   [2:4]     Fixed header length (8, Big-Endian)
 *   [4:12]    Fixed header (fields + padding, Big-Endian encoded)
 *   [12:end]  Dynamic payload (variable-length field data)
 */
int read_response_marshal(const read_response_t* msg, uint8_t** out_buf) {
    if (!msg || !out_buf) return -1;

    /* Calculate total dynamic payload size from all variable-length fields */
    size_t dyn_size = 0;
    dyn_size += msg->data_len;

    size_t total = WIRE_FRAME_HEADER_SIZE + READ_RESPONSE_FIXED_SIZE + dyn_size;
    if (total > MAX_ALLOWED_PACKET) return -1;

    uint8_t* buf = (uint8_t*)malloc(total);
    if (!buf) return -1;

    memset(buf, 0, WIRE_FRAME_HEADER_SIZE + READ_RESPONSE_FIXED_SIZE);

    /* Write wire frame header identifiers */
    put_u16_be(buf, READ_RESPONSE_TYPE_ID);
    put_u16_be(buf + WIRE_FRAME_MSG_TYPE_SIZE, READ_RESPONSE_FIXED_SIZE);

    uint8_t* hdr = buf + WIRE_FRAME_HEADER_SIZE;
    size_t dyn_off = WIRE_FRAME_HEADER_SIZE + READ_RESPONSE_FIXED_SIZE;
    put_u32_be(hdr + 0, (uint32_t)msg->bytes_read);
    put_u32_be(hdr + 4, msg->data_len);
    if (msg->data_len > 0 && msg->data) {
        memcpy(buf + dyn_off, msg->data, msg->data_len);
        dyn_off += msg->data_len;
    }

    (void)dyn_off;
    *out_buf = buf;
    return (int)total;
}

/**
 * read_response_unmarshal - Deserialize ReadResponse from a contiguous buffer.
 *
 * in_buf points to the start of the fixed header (after the 4-byte frame header).
 * Variable-length fields are malloc'd; caller must call read_response_free().
 * On any error, partial allocations are cleaned up before returning.
 */
int read_response_unmarshal(const uint8_t* in_buf, size_t in_len, uint16_t fixed_header_len, read_response_t* out_msg) {
    if (!in_buf || !out_msg ||
        fixed_header_len < READ_RESPONSE_FIXED_SIZE ||
        in_len < fixed_header_len ||
        in_len > MAX_ALLOWED_PACKET) {
        return -1;
    }

    memset(out_msg, 0, sizeof(read_response_t));

    const uint8_t* hdr = in_buf;
    size_t dyn_off = fixed_header_len;

    /* Decode fixed-size primitives from structural block offsets */
    out_msg->bytes_read = (int32_t)get_u32_be(hdr + 0);
    out_msg->data_len = get_u32_be(hdr + 4);

    /* Decode variable-length dynamic fields safely */
    if (out_msg->data_len > 0) {
        if (out_msg->data_len > MAX_ALLOWED_PACKET || dyn_off + out_msg->data_len > in_len) {
            read_response_free(out_msg);
            return -1;
        }
        out_msg->data = (char*) malloc(out_msg->data_len + 1);
        if (!out_msg->data) {
            read_response_free(out_msg);
            return -1;
        }

        memcpy(out_msg->data, in_buf + dyn_off, out_msg->data_len);
        out_msg->data[out_msg->data_len] = '\0';
        dyn_off += out_msg->data_len;
    }

    (void)dyn_off;
    return 0;
}

/**
 * read_response_free - Release heap memory owned by a read_response_t struct.
 */
void read_response_free(read_response_t* msg) {
    if (!msg) return;
    if (msg->data) {
        free(msg->data);
        msg->data = NULL;
    }
    msg->data_len = 0;
}


/* ===========================================================================
 * WriteRequest (Type ID: 3, Fixed Header: 12 bytes)
 * ===========================================================================*/

/**
 * Sets the value of the offset field in the write_request_t struct.
 */
void write_request_set_offset(write_request_t* msg, const int32_t value) {
    if (msg) msg->offset = value;
}

/**
 * Sets the value of the data field in the write_request_t struct.
 */
void write_request_set_data(write_request_t* msg, const char* value) {
    if (!msg || !value) return;
    if (msg->data != NULL) {
        free(msg->data);
    }

    size_t len = strlen(value);
    char* new_value = (char*) malloc(len + 1);
    if (!new_value) return;

    memcpy(new_value, value, len + 1);
    msg->data = new_value;
    msg->data_len = (uint32_t)len;
}

/**
 * Sets the value of the key field in the write_request_t struct.
 */
void write_request_set_key(write_request_t* msg, const char* value) {
    if (!msg || !value) return;
    if (msg->key != NULL) {
        free(msg->key);
    }

    size_t len = strlen(value);
    char* new_value = (char*) malloc(len + 1);
    if (!new_value) return;

    memcpy(new_value, value, len + 1);
    msg->key = new_value;
    msg->key_len = (uint32_t)len;
}

/**
 * calculate_write_request_dynamic_payload_size - Compute the total size of
 * all variable-length fields in the WriteRequest message from the fixed header.
 */
size_t calculate_write_request_dynamic_payload_size(const uint8_t* hdr_buf) {
    if (!hdr_buf) return 0;
    size_t dyn_total = 0;
    uint32_t data_len = get_u32_be(hdr_buf + 4);
    dyn_total += data_len;
    uint32_t key_len = get_u32_be(hdr_buf + 8);
    dyn_total += key_len;
    return dyn_total;
}

/**
 * write_request_marshal - Serialize WriteRequest to wire format.
 *
 * Writes the complete framed message into out_buf:
 *   [0:2]     Type ID (3, Big-Endian)
 *   [2:4]     Fixed header length (12, Big-Endian)
 *   [4:16]    Fixed header (fields + padding, Big-Endian encoded)
 *   [16:end]  Dynamic payload (variable-length field data)
 */
int write_request_marshal(const write_request_t* msg, uint8_t** out_buf) {
    if (!msg || !out_buf) return -1;

    /* Calculate total dynamic payload size from all variable-length fields */
    size_t dyn_size = 0;
    dyn_size += msg->data_len;
    dyn_size += msg->key_len;

    size_t total = WIRE_FRAME_HEADER_SIZE + WRITE_REQUEST_FIXED_SIZE + dyn_size;
    if (total > MAX_ALLOWED_PACKET) return -1;

    uint8_t* buf = (uint8_t*)malloc(total);
    if (!buf) return -1;

    memset(buf, 0, WIRE_FRAME_HEADER_SIZE + WRITE_REQUEST_FIXED_SIZE);

    /* Write wire frame header identifiers */
    put_u16_be(buf, WRITE_REQUEST_TYPE_ID);
    put_u16_be(buf + WIRE_FRAME_MSG_TYPE_SIZE, WRITE_REQUEST_FIXED_SIZE);

    uint8_t* hdr = buf + WIRE_FRAME_HEADER_SIZE;
    size_t dyn_off = WIRE_FRAME_HEADER_SIZE + WRITE_REQUEST_FIXED_SIZE;
    put_u32_be(hdr + 0, (uint32_t)msg->offset);
    put_u32_be(hdr + 4, msg->data_len);
    if (msg->data_len > 0 && msg->data) {
        memcpy(buf + dyn_off, msg->data, msg->data_len);
        dyn_off += msg->data_len;
    }
    put_u32_be(hdr + 8, msg->key_len);
    if (msg->key_len > 0 && msg->key) {
        memcpy(buf + dyn_off, msg->key, msg->key_len);
        dyn_off += msg->key_len;
    }

    (void)dyn_off;
    *out_buf = buf;
    return (int)total;
}

/**
 * write_request_unmarshal - Deserialize WriteRequest from a contiguous buffer.
 *
 * in_buf points to the start of the fixed header (after the 4-byte frame header).
 * Variable-length fields are malloc'd; caller must call write_request_free().
 * On any error, partial allocations are cleaned up before returning.
 */
int write_request_unmarshal(const uint8_t* in_buf, size_t in_len, uint16_t fixed_header_len, write_request_t* out_msg) {
    if (!in_buf || !out_msg ||
        fixed_header_len < WRITE_REQUEST_FIXED_SIZE ||
        in_len < fixed_header_len ||
        in_len > MAX_ALLOWED_PACKET) {
        return -1;
    }

    memset(out_msg, 0, sizeof(write_request_t));

    const uint8_t* hdr = in_buf;
    size_t dyn_off = fixed_header_len;

    /* Decode fixed-size primitives from structural block offsets */
    out_msg->offset = (int32_t)get_u32_be(hdr + 0);
    out_msg->data_len = get_u32_be(hdr + 4);
    out_msg->key_len = get_u32_be(hdr + 8);

    /* Decode variable-length dynamic fields safely */
    if (out_msg->data_len > 0) {
        if (out_msg->data_len > MAX_ALLOWED_PACKET || dyn_off + out_msg->data_len > in_len) {
            write_request_free(out_msg);
            return -1;
        }
        out_msg->data = (char*) malloc(out_msg->data_len + 1);
        if (!out_msg->data) {
            write_request_free(out_msg);
            return -1;
        }

        memcpy(out_msg->data, in_buf + dyn_off, out_msg->data_len);
        out_msg->data[out_msg->data_len] = '\0';
        dyn_off += out_msg->data_len;
    }
    if (out_msg->key_len > 0) {
        if (out_msg->key_len > MAX_ALLOWED_PACKET || dyn_off + out_msg->key_len > in_len) {
            write_request_free(out_msg);
            return -1;
        }
        out_msg->key = (char*) malloc(out_msg->key_len + 1);
        if (!out_msg->key) {
            write_request_free(out_msg);
            return -1;
        }

        memcpy(out_msg->key, in_buf + dyn_off, out_msg->key_len);
        out_msg->key[out_msg->key_len] = '\0';
        dyn_off += out_msg->key_len;
    }

    (void)dyn_off;
    return 0;
}

/**
 * write_request_free - Release heap memory owned by a write_request_t struct.
 */
void write_request_free(write_request_t* msg) {
    if (!msg) return;
    if (msg->data) {
        free(msg->data);
        msg->data = NULL;
    }
    msg->data_len = 0;
    if (msg->key) {
        free(msg->key);
        msg->key = NULL;
    }
    msg->key_len = 0;
}


/* ===========================================================================
 * WriteResponse (Type ID: 4, Fixed Header: 4 bytes)
 * ===========================================================================*/

/**
 * Sets the value of the bytes_written field in the write_response_t struct.
 */
void write_response_set_bytes_written(write_response_t* msg, const int32_t value) {
    if (msg) msg->bytes_written = value;
}

/**
 * calculate_write_response_dynamic_payload_size - Compute the total size of
 * all variable-length fields in the WriteResponse message from the fixed header.
 */
size_t calculate_write_response_dynamic_payload_size(const uint8_t* hdr_buf) {
    if (!hdr_buf) return 0;
    size_t dyn_total = 0;
    return dyn_total;
}

/**
 * write_response_marshal - Serialize WriteResponse to wire format.
 *
 * Writes the complete framed message into out_buf:
 *   [0:2]     Type ID (4, Big-Endian)
 *   [2:4]     Fixed header length (4, Big-Endian)
 *   [4:8]    Fixed header (fields + padding, Big-Endian encoded)
 *   [8:end]  Dynamic payload (variable-length field data)
 */
int write_response_marshal(const write_response_t* msg, uint8_t** out_buf) {
    if (!msg || !out_buf) return -1;

    /* Calculate total dynamic payload size from all variable-length fields */
    size_t dyn_size = 0;

    size_t total = WIRE_FRAME_HEADER_SIZE + WRITE_RESPONSE_FIXED_SIZE + dyn_size;
    if (total > MAX_ALLOWED_PACKET) return -1;

    uint8_t* buf = (uint8_t*)malloc(total);
    if (!buf) return -1;

    memset(buf, 0, WIRE_FRAME_HEADER_SIZE + WRITE_RESPONSE_FIXED_SIZE);

    /* Write wire frame header identifiers */
    put_u16_be(buf, WRITE_RESPONSE_TYPE_ID);
    put_u16_be(buf + WIRE_FRAME_MSG_TYPE_SIZE, WRITE_RESPONSE_FIXED_SIZE);

    uint8_t* hdr = buf + WIRE_FRAME_HEADER_SIZE;
    size_t dyn_off = WIRE_FRAME_HEADER_SIZE + WRITE_RESPONSE_FIXED_SIZE;
    put_u32_be(hdr + 0, (uint32_t)msg->bytes_written);

    (void)dyn_off;
    *out_buf = buf;
    return (int)total;
}

/**
 * write_response_unmarshal - Deserialize WriteResponse from a contiguous buffer.
 *
 * in_buf points to the start of the fixed header (after the 4-byte frame header).
 * Variable-length fields are malloc'd; caller must call write_response_free().
 * On any error, partial allocations are cleaned up before returning.
 */
int write_response_unmarshal(const uint8_t* in_buf, size_t in_len, uint16_t fixed_header_len, write_response_t* out_msg) {
    if (!in_buf || !out_msg ||
        fixed_header_len < WRITE_RESPONSE_FIXED_SIZE ||
        in_len < fixed_header_len ||
        in_len > MAX_ALLOWED_PACKET) {
        return -1;
    }

    memset(out_msg, 0, sizeof(write_response_t));

    const uint8_t* hdr = in_buf;
    size_t dyn_off = fixed_header_len;

    /* Decode fixed-size primitives from structural block offsets */
    out_msg->bytes_written = (int32_t)get_u32_be(hdr + 0);

    /* Decode variable-length dynamic fields safely */

    (void)dyn_off;
    return 0;
}

/**
 * write_response_free - Release heap memory owned by a write_response_t struct.
 */
void write_response_free(write_response_t* msg) {
    if (!msg) return;
}


