/*
 * DO NOT EDIT THIS FILE.
 * Code generated by wireforge.
 *
 * This header defines C structure types and function prototypes for a
 * length-prefixed binary wire protocol. Each message type has:
 *
 *   - A typedef struct with explicit padding fields for deterministic layout
 *   - _Static_assert to verify struct size at compile time
 *   - Marshal/Unmarshal functions for buffer-based serialization
 *   - Stream-safe read/write functions for socket I/O (handles short reads)
 *   - A free function to release dynamically allocated fields
 *
 * Wire Protocol Frame Layout:
 *   +--------+------------------+-------------------+------------------+
 *   | Offset | Field            | Type              | Description      |
 *   +--------+------------------+-------------------+------------------+
 *   | 0      | Message Type ID  | uint16 Big-Endian | Codec selector   |
 *   | 2      | Fixed Header Len | uint16 Big-Endian | Fixed block size |
 *   | 4      | Fixed Header     | raw bytes         | Padded fields    |
 *   | 4+N    | Dynamic Payload  | raw bytes         | Strings/blobs    |
 *   +--------+------------------+-------------------+------------------+
 *
 * Safety guarantees:
 *   - MAX_ALLOWED_PACKET caps any single allocation (prevents malloc bombs)
 *   - NULL checks on every allocation result
 *   - Strings are always NULL-terminated after deserialization
 *   - free functions set pointers to NULL to prevent double-free
 *
 * Memory ownership:
 *   - After unmarshal, the caller owns the struct and must call
 *     the corresponding _free() function when done.
 *   - After marshal, no heap memory is retained by the callee.
 */
#ifndef MESSAGES_H
#define MESSAGES_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Maximum allowed packet size (16 MB).
 * Any length field exceeding this is treated as data corruption and
 * immediately rejected to prevent denial-of-service via malloc bombs.
 */
#define MAX_ALLOWED_PACKET (16 * 1024 * 1024)

#define WIRE_FRAME_MSG_TYPE_SIZE 2
#define WIRE_FRAME_MSG_FIXED_SIZE 2

/** Size of the wire frame header: 2-byte type ID + 2-byte fixed header length. */
#define WIRE_FRAME_HEADER_SIZE 4

uint16_t get_message_type(const uint8_t* buf);
uint16_t get_message_fixed_length(const uint8_t* buf);


/* ===========================================================================
 * ReadRequest
 * Wire Type ID: 1
 * Fixed Header: 12 bytes (including alignment padding)
 * ===========================================================================*/

/** Wire protocol message type ID for ReadRequest. */
#define READ_REQUEST_TYPE_ID 1

/** Byte size of the fixed header block for ReadRequest (padded for alignment). */
#define READ_REQUEST_FIXED_SIZE 12

/**
 * read_request_t - Wire-serializable message structure.
 *
 * Fixed-size fields are stored inline. Variable-length fields (strings, byte
 * arrays) are represented as a uint32 length prefix plus a heap-allocated
 * pointer. Explicit padding fields (_padN) ensure the struct has a
 * deterministic memory layout matching the wire format regardless of compiler.
 *
 * IMPORTANT: Do not reorder fields. The layout must match the wire format.
 */
typedef struct {
    /** The number of bytes to read. */
    int32_t count;
    /** The offset in the file to start reading from. */
    int32_t offset;
    /** Object key to perform read operation. (length of dynamic payload below). */
    uint32_t key_len;
    char* key;     /**< Heap-allocated; call readrequest_free() when done. */
} read_request_t;

/* Compile-time size check: catch layout mismatches before runtime. */
_Static_assert(sizeof(read_request_t) >= 12,
    "wireforge: read_request_t fixed layout size mismatch");

/**
 * Sets the value of the count field in the read_request_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void read_request_set_count(read_request_t* msg, const int32_t value);

/**
 * Sets the value of the offset field in the read_request_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void read_request_set_offset(read_request_t* msg, const int32_t value);

/**
 * Sets the value of the key field in the read_request_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void read_request_set_key(read_request_t* msg, const char* value);

/**
 * calculate_read_request_dynamic_payload_size - Compute the total size of
 * all variable-length fields in the ReadRequest message from the fixed header.
 */
size_t calculate_read_request_dynamic_payload_size(const uint8_t* hdr_buf);

/**
 * Serialize a ReadRequest message into out_buf in wire format.
 *
 * @param msg       Pointer to the message to serialize (must not be NULL).
 * @param out_buf   Pointer to the destination byte buffer pointer. The function 
 * 					will write the serialized message stream into the buffer referenced 
 * 					by this address.
 * @return          Total bytes written on success, or -1 on error
 *                  (NULL pointer, buffer too small, exceeds MAX_ALLOWED_PACKET).
 */
int read_request_marshal(const read_request_t* msg, uint8_t** out_buf);

/**
 * Deserialize a ReadRequest message from a contiguous buffer.
 *
 * @param in_buf           Input buffer starting at the fixed header (after frame header).
 * @param in_len           Total available bytes in in_buf (fixed header + dynamic payload).
 * @param fixed_header_len Fixed header length as read from the wire frame header.
 * @param out_msg          Output struct (zeroed on entry; fields populated on success).
 * @return                 0 on success, -1 on error (truncated data, allocation failure,
 *                         length exceeds MAX_ALLOWED_PACKET).
 *
 * On success, caller MUST call read_request_free(out_msg) when done to release
 * any heap-allocated variable-length fields.
 */
int read_request_unmarshal(const uint8_t* in_buf, size_t in_len, uint16_t fixed_header_len, read_request_t* out_msg);

/**
 * Free all dynamically allocated fields in a read_request_t struct.
 *
 * Safe to call multiple times: pointers are set to NULL and lengths to 0
 * after release. Does NOT free the struct itself (caller manages lifetime).
 *
 * @param msg  Pointer to the struct to clean up (NULL is a safe no-op).
 */
void read_request_free(read_request_t* msg);


/* ===========================================================================
 * ReadResponse
 * Wire Type ID: 2
 * Fixed Header: 8 bytes (including alignment padding)
 * ===========================================================================*/

/** Wire protocol message type ID for ReadResponse. */
#define READ_RESPONSE_TYPE_ID 2

/** Byte size of the fixed header block for ReadResponse (padded for alignment). */
#define READ_RESPONSE_FIXED_SIZE 8

/**
 * read_response_t - Wire-serializable message structure.
 *
 * Fixed-size fields are stored inline. Variable-length fields (strings, byte
 * arrays) are represented as a uint32 length prefix plus a heap-allocated
 * pointer. Explicit padding fields (_padN) ensure the struct has a
 * deterministic memory layout matching the wire format regardless of compiler.
 *
 * IMPORTANT: Do not reorder fields. The layout must match the wire format.
 */
typedef struct {
    /** The actual number of bytes read from the file. */
    int32_t bytes_read;
    /** The data read from the file, encoded in base64. (length of dynamic payload below). */
    uint32_t data_len;
    char* data;     /**< Heap-allocated; call readresponse_free() when done. */
} read_response_t;

/* Compile-time size check: catch layout mismatches before runtime. */
_Static_assert(sizeof(read_response_t) >= 8,
    "wireforge: read_response_t fixed layout size mismatch");

/**
 * Sets the value of the bytes_read field in the read_response_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void read_response_set_bytes_read(read_response_t* msg, const int32_t value);

/**
 * Sets the value of the data field in the read_response_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void read_response_set_data(read_response_t* msg, const char* value);

/**
 * calculate_read_response_dynamic_payload_size - Compute the total size of
 * all variable-length fields in the ReadResponse message from the fixed header.
 */
size_t calculate_read_response_dynamic_payload_size(const uint8_t* hdr_buf);

/**
 * Serialize a ReadResponse message into out_buf in wire format.
 *
 * @param msg       Pointer to the message to serialize (must not be NULL).
 * @param out_buf   Pointer to the destination byte buffer pointer. The function 
 * 					will write the serialized message stream into the buffer referenced 
 * 					by this address.
 * @return          Total bytes written on success, or -1 on error
 *                  (NULL pointer, buffer too small, exceeds MAX_ALLOWED_PACKET).
 */
int read_response_marshal(const read_response_t* msg, uint8_t** out_buf);

/**
 * Deserialize a ReadResponse message from a contiguous buffer.
 *
 * @param in_buf           Input buffer starting at the fixed header (after frame header).
 * @param in_len           Total available bytes in in_buf (fixed header + dynamic payload).
 * @param fixed_header_len Fixed header length as read from the wire frame header.
 * @param out_msg          Output struct (zeroed on entry; fields populated on success).
 * @return                 0 on success, -1 on error (truncated data, allocation failure,
 *                         length exceeds MAX_ALLOWED_PACKET).
 *
 * On success, caller MUST call read_response_free(out_msg) when done to release
 * any heap-allocated variable-length fields.
 */
int read_response_unmarshal(const uint8_t* in_buf, size_t in_len, uint16_t fixed_header_len, read_response_t* out_msg);

/**
 * Free all dynamically allocated fields in a read_response_t struct.
 *
 * Safe to call multiple times: pointers are set to NULL and lengths to 0
 * after release. Does NOT free the struct itself (caller manages lifetime).
 *
 * @param msg  Pointer to the struct to clean up (NULL is a safe no-op).
 */
void read_response_free(read_response_t* msg);


/* ===========================================================================
 * WriteRequest
 * Wire Type ID: 3
 * Fixed Header: 12 bytes (including alignment padding)
 * ===========================================================================*/

/** Wire protocol message type ID for WriteRequest. */
#define WRITE_REQUEST_TYPE_ID 3

/** Byte size of the fixed header block for WriteRequest (padded for alignment). */
#define WRITE_REQUEST_FIXED_SIZE 12

/**
 * write_request_t - Wire-serializable message structure.
 *
 * Fixed-size fields are stored inline. Variable-length fields (strings, byte
 * arrays) are represented as a uint32 length prefix plus a heap-allocated
 * pointer. Explicit padding fields (_padN) ensure the struct has a
 * deterministic memory layout matching the wire format regardless of compiler.
 *
 * IMPORTANT: Do not reorder fields. The layout must match the wire format.
 */
typedef struct {
    /** The offset in the file to start writing to. */
    int32_t offset;
    /** The data to write to the file, encoded in base64. (length of dynamic payload below). */
    uint32_t data_len;
    char* data;     /**< Heap-allocated; call writerequest_free() when done. */
    /** Object key to perform write operation. (length of dynamic payload below). */
    uint32_t key_len;
    char* key;     /**< Heap-allocated; call writerequest_free() when done. */
} write_request_t;

/* Compile-time size check: catch layout mismatches before runtime. */
_Static_assert(sizeof(write_request_t) >= 12,
    "wireforge: write_request_t fixed layout size mismatch");

/**
 * Sets the value of the offset field in the write_request_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void write_request_set_offset(write_request_t* msg, const int32_t value);

/**
 * Sets the value of the data field in the write_request_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void write_request_set_data(write_request_t* msg, const char* value);

/**
 * Sets the value of the key field in the write_request_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void write_request_set_key(write_request_t* msg, const char* value);

/**
 * calculate_write_request_dynamic_payload_size - Compute the total size of
 * all variable-length fields in the WriteRequest message from the fixed header.
 */
size_t calculate_write_request_dynamic_payload_size(const uint8_t* hdr_buf);

/**
 * Serialize a WriteRequest message into out_buf in wire format.
 *
 * @param msg       Pointer to the message to serialize (must not be NULL).
 * @param out_buf   Pointer to the destination byte buffer pointer. The function 
 * 					will write the serialized message stream into the buffer referenced 
 * 					by this address.
 * @return          Total bytes written on success, or -1 on error
 *                  (NULL pointer, buffer too small, exceeds MAX_ALLOWED_PACKET).
 */
int write_request_marshal(const write_request_t* msg, uint8_t** out_buf);

/**
 * Deserialize a WriteRequest message from a contiguous buffer.
 *
 * @param in_buf           Input buffer starting at the fixed header (after frame header).
 * @param in_len           Total available bytes in in_buf (fixed header + dynamic payload).
 * @param fixed_header_len Fixed header length as read from the wire frame header.
 * @param out_msg          Output struct (zeroed on entry; fields populated on success).
 * @return                 0 on success, -1 on error (truncated data, allocation failure,
 *                         length exceeds MAX_ALLOWED_PACKET).
 *
 * On success, caller MUST call write_request_free(out_msg) when done to release
 * any heap-allocated variable-length fields.
 */
int write_request_unmarshal(const uint8_t* in_buf, size_t in_len, uint16_t fixed_header_len, write_request_t* out_msg);

/**
 * Free all dynamically allocated fields in a write_request_t struct.
 *
 * Safe to call multiple times: pointers are set to NULL and lengths to 0
 * after release. Does NOT free the struct itself (caller manages lifetime).
 *
 * @param msg  Pointer to the struct to clean up (NULL is a safe no-op).
 */
void write_request_free(write_request_t* msg);


/* ===========================================================================
 * WriteResponse
 * Wire Type ID: 4
 * Fixed Header: 4 bytes (including alignment padding)
 * ===========================================================================*/

/** Wire protocol message type ID for WriteResponse. */
#define WRITE_RESPONSE_TYPE_ID 4

/** Byte size of the fixed header block for WriteResponse (padded for alignment). */
#define WRITE_RESPONSE_FIXED_SIZE 4

/**
 * write_response_t - Wire-serializable message structure.
 *
 * Fixed-size fields are stored inline. Variable-length fields (strings, byte
 * arrays) are represented as a uint32 length prefix plus a heap-allocated
 * pointer. Explicit padding fields (_padN) ensure the struct has a
 * deterministic memory layout matching the wire format regardless of compiler.
 *
 * IMPORTANT: Do not reorder fields. The layout must match the wire format.
 */
typedef struct {
    /** The actual number of bytes written to the file. */
    int32_t bytes_written;
} write_response_t;

/* Compile-time size check: catch layout mismatches before runtime. */
_Static_assert(sizeof(write_response_t) >= 4,
    "wireforge: write_response_t fixed layout size mismatch");

/**
 * Sets the value of the bytes_written field in the write_response_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void write_response_set_bytes_written(write_response_t* msg, const int32_t value);

/**
 * calculate_write_response_dynamic_payload_size - Compute the total size of
 * all variable-length fields in the WriteResponse message from the fixed header.
 */
size_t calculate_write_response_dynamic_payload_size(const uint8_t* hdr_buf);

/**
 * Serialize a WriteResponse message into out_buf in wire format.
 *
 * @param msg       Pointer to the message to serialize (must not be NULL).
 * @param out_buf   Pointer to the destination byte buffer pointer. The function 
 * 					will write the serialized message stream into the buffer referenced 
 * 					by this address.
 * @return          Total bytes written on success, or -1 on error
 *                  (NULL pointer, buffer too small, exceeds MAX_ALLOWED_PACKET).
 */
int write_response_marshal(const write_response_t* msg, uint8_t** out_buf);

/**
 * Deserialize a WriteResponse message from a contiguous buffer.
 *
 * @param in_buf           Input buffer starting at the fixed header (after frame header).
 * @param in_len           Total available bytes in in_buf (fixed header + dynamic payload).
 * @param fixed_header_len Fixed header length as read from the wire frame header.
 * @param out_msg          Output struct (zeroed on entry; fields populated on success).
 * @return                 0 on success, -1 on error (truncated data, allocation failure,
 *                         length exceeds MAX_ALLOWED_PACKET).
 *
 * On success, caller MUST call write_response_free(out_msg) when done to release
 * any heap-allocated variable-length fields.
 */
int write_response_unmarshal(const uint8_t* in_buf, size_t in_len, uint16_t fixed_header_len, write_response_t* out_msg);

/**
 * Free all dynamically allocated fields in a write_response_t struct.
 *
 * Safe to call multiple times: pointers are set to NULL and lengths to 0
 * after release. Does NOT free the struct itself (caller manages lifetime).
 *
 * @param msg  Pointer to the struct to clean up (NULL is a safe no-op).
 */
void write_response_free(write_response_t* msg);


#ifdef __cplusplus
}
#endif

#endif /* MESSAGES_H */
